version: '3'

services:
  s_billiard:
    build:
      context: ./
      dockerfile: dev.dockerfile
      args:
        workdir: /files/billiard
    ports:
      - 8000:8000
    volumes:
      - ./:/files/billiard
      - v_billiard:/files/billiard/node_modules
    restart: always

volumes:
  v_billiard:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
